---

# Create new user and add authorized key to log in

- name: create non-root user group
  group:
    name: "{{ deploy_group }}"
    state: present

- name: create non-root user
  user:
    name:  "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    shell: "{{ shell_used }}"
    state: present

- name: add authorized_key for non-root user
  authorized_key:
    user: deployer
    state: present
    key: "{{ lookup('file', authorized_key_filename )}}"
