# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Using DHCP
  # config.vm.network "private_network", type: "dhcp"

  # Using static
   #config.vm.network "private_network", ip: "10.10.10.10"

  # Using the Public network with DHCP have to select the network
    # config.vm.network "public_network"

  # using the public_network with DHCP but adding the network to use
  #  config.vm.network "public_network", use_dhcp_assigned_default_route: true

  # Using the public_network with Static IP
  #  config.vm.network "public_network", ip: "192.168.1.123"

  # Stop responding to question about what bridge
  #  config.vm.network "public_network", use_dhcp_assigned_default_route: true,
  #    bridge: "en7: Thunderbolt Ethernet"

  # Stop responding to question about what bridge
    config.vm.network "public_network", use_dhcp_assigned_default_route: true,
      bridge: "en0: Wi-Fi (AirPort)"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install  -y nginx
  SHELL
end
