# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Using DHCP
  # config.vm.network "private_network", type: "dhcp"
  # Using static IP
  config.vm.network "private_network", ip: "10.10.10.10"
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install  -y nginx
  SHELL
end
