# clone our source code repo onto our server
- name: ensure Git is installed
  apt: name=git state=present cache_valid_time=3600
  become: yes

- name: create the deploy key directory
  file: path=/home/{{ deploy_user }}/git_deploy_key state=directory

- name: esure deploy key is on the remote server
  copy: src={{ local_deploy_key_dir }}/{{ read_only_deploy_key_name }}
        dest=/home/{{ deploy_user }}/git_deploy_key/{{ read_only_deploy_key_name }}
        mode=600 owner={{ deploy_user }} group={{ deploy_group }}

- name: clone or pull latest code
  git: repo={{ code_repository }} dest={{ app_dir }}
       key_file=/home/{{ deploy_user }}/git_deploy_key/{{ read_only_deploy_key_name }}
       accept_hostkey=yes
