# install and configure nginx
- name: insure nginx is installed
  apt: name=nginx state=present cache_valid_time=3600
  become: yes

- name: write custom Nginx configuration
  template: src=nginx_conf.j2
            dest=/etc/nginx/conf.d/app.conf
  become: yes
