# install security configuration
- name: ensure python packages are installed
  apt:
    name: [ "python3-pip",
            "python3-dev",
            "fail2ban"
          ]
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: enable SSH within the firewall
  ufw: "rule=allow port=22"
  become: yes

- name: enable firewall
  ufw: state=enabled
  become: yes
